export interface Member {
  isOnline: boolean | undefined
  id: string
  name: string
  firstName: string
  lastName: string
  email: string
  phone: string
  field: string
  year: number
  motivation: string
  projects: string
  skills: string
  status: "online" | "offline"
  avatar: string
  points: number
  role?: string
  isBureau?: boolean
}

export const members: Member[] = [
  {
    id: "1",
    name: "Mohamed Aziz Mehri",
    firstName: "Mohamed Aziz",
    lastName: "Mehri",
    email: "aziz.mehri@radioistic.tn",
    phone: "+216 12 345 678",
    field: "GLSI",
    year: 3,
    motivation: "Responsable de la vision stratégique et de la coordination générale du club",
    projects: "Gestion du club, organisation d'événements majeurs",
    skills: "Leadership, Communication, Organisation, Vision stratégique",
    status: "online",
    avatar: "/avatars/aziz-mehri.png",
    points: 2500,
    role: "Président",
    isBureau: true,
  },
  {
    id: "2",
    name: "Nassim Ben Mrad",
    firstName: "Nassim",
    lastName: "Ben Mrad",
    email: "nassim.benmrad@radioistic.tn",
    phone: "+216 23 456 789",
    field: "GLSI",
    year: 3,
    motivation: "Support au président et coordination des équipes",
    projects: "Coordination inter-équipes, gestion de projets",
    skills: "Organisation, Gestion d'équipe, Coordination",
    status: "online",
    avatar: "/avatars/nassim-benmrad.png",
    points: 2300,
    role: "Vice-président",
    isBureau: true,
  },
  {
    id: "3",
    name: "Balkis",
    firstName: "Balkis",
    lastName: "Secretaire",
    email: "balkis@radioistic.tn",
    phone: "+216 34 567 890",
    field: "GLSI",
    year: 3,
    motivation: "Gestion administrative et documentation du club",
    projects: "Documentation, procès-verbaux, archives",
    skills: "Rédaction, Organisation, Gestion administrative",
    status: "offline",
    avatar: "/avatars/balkis.png",
    points: 2100,
    role: "Secrétaire Générale",
    isBureau: true,
  },
  {
    id: "4",
    name: "Mohamed Sahly",
    firstName: "Mohamed",
    lastName: "Sahly",
    email: "mohamed.sahly@radioistic.tn",
    phone: "+216 45 678 901",
    field: "GLSI",
    year: 3,
    motivation: "Développement des partenariats et relations avec les sponsors",
    projects: "Recherche de sponsors, partenariats stratégiques",
    skills: "Négociation, Communication, Développement commercial",
    status: "online",
    avatar: "/avatars/mohamed-sahly.png",
    points: 1900,
    role: "Responsable Sponsors",
    isBureau: true,
  },
  {
    id: "5",
    name: "Aymen Ksouri",
    firstName: "Aymen",
    lastName: "Ksouri",
    email: "aymen.ksouri@radioistic.tn",
    phone: "+216 56 789 012",
    field: "GLSI",
    year: 3,
    motivation: "Organisation et coordination de tous les événements du club",
    projects: "Tournois, soirées, voyages, événements majeurs",
    skills: "Organisation d'événements, Logistique, Gestion de projet",
    status: "online",
    avatar: "/avatars/aymen-ksouri.png",
    points: 2200,
    role: "Responsable Événements",
    isBureau: true,
  },
  {
    id: "6",
    name: "Dhia Eddine Ktiti",
    firstName: "Dhia Eddine",
    lastName: "Ktiti",
    email: "dhia.ktiti@radioistic.tn",
    phone: "+216 67 890 123",
    field: "GLSI",
    year: 3,
    motivation: "Production de contenu et gestion des réseaux sociaux",
    projects: "Podcasts, vidéos, photos, gestion social media",
    skills: "Production média, Montage, Design, Community management",
    status: "online",
    avatar: "/avatars/dhia-ktiti.png",
    points: 2000,
    role: "Responsable Média",
    isBureau: true,
  },
  {
    id: "7",
    name: "Maram El kamel",
    firstName: "Maram",
    lastName: "El kamel",
    email: "eikametmaramf6@gmail.com",
    phone: "+216 21 687 503",
    field: "GLSI",
    year: 3,
    motivation: "3ajjaw",
    projects: "Podcast anonyme (with voice changer and no names) topics : istic hater vibe",
    skills: "Tbh barcha hajet",
    status: "online",
    avatar: "/avatars/maram-elkamel.png",
    points: 850,
  },
  {
    id: "8",
    name: "Miniar Mahar",
    firstName: "Miniar",
    lastName: "Mahar",
    email: "mnimmina0@gmail.com",
    phone: "+216 50 827 899",
    field: "GLSI",
    year: 3,
    motivation: "Membre actif de Radio Istic",
    projects: "En cours de développement",
    skills: "En développement",
    status: "offline",
    avatar: "/avatars/miniar-mahar.png",
    points: 650,
  },
  {
    id: "9",
    name: "Amen Amon",
    firstName: "Amen",
    lastName: "Amon",
    email: "amenkhalfi0@gmail.com",
    phone: "+216 20 041 436",
    field: "GLSI",
    year: 3,
    motivation: "Manedrouch",
    projects: "Podcast m3a ai version men Shrek",
    skills: "Créativité",
    status: "online",
    avatar: "/avatars/amen-amon.png",
    points: 720,
  },
  {
    id: "10",
    name: "Abdallah Aksislah",
    firstName: "Abdallah",
    lastName: "Aksislah",
    email: "zreliLabdullah19@gmail.com",
    phone: "+216 52 623 729",
    field: "GLSI",
    year: 3,
    motivation: "3al zab",
    projects: "Basketball Tournament",
    skills: "Sport, Organisation",
    status: "offline",
    avatar: "/avatars/abdallah-aksislah.png",
    points: 680,
  },
  {
    id: "11",
    name: "Adam Kaboubi",
    firstName: "Adam",
    lastName: "Kaboubi",
    email: "Ademkaboub54@gmail.com",
    phone: "+216 95 268 116",
    field: "GLSI",
    year: 3,
    motivation: "For fun",
    projects: "En cours",
    skills: "En développement",
    status: "online",
    avatar: "/avatars/adam-kaboubi.png",
    points: 550,
  },
  {
    id: "12",
    name: "Malek Ben zalee",
    firstName: "Malek",
    lastName: "Ben zalee",
    email: "Malekkaaeo@gmail.com",
    phone: "+216 24 119 359",
    field: "IRS",
    year: 2,
    motivation: "Membre de Radio Istic",
    projects: "En cours",
    skills: "En développement",
    status: "offline",
    avatar: "/avatars/malek-benzalee.png",
    points: 420,
  },
  {
    id: "13",
    name: "Anas Kiskat",
    firstName: "Anas",
    lastName: "Kiskat",
    email: "anekskaks19@gmail.com",
    phone: "+216 95 631 632",
    field: "GLSI",
    year: 3,
    motivation: "Membre actif",
    projects: "En cours",
    skills: "En développement",
    status: "online",
    avatar: "/avatars/anas-kiskat.png",
    points: 380,
  },
  {
    id: "14",
    name: "Ghrir Yomma",
    firstName: "Ghrir",
    lastName: "Yomma",
    email: "yomengivir107@gmail.com",
    phone: "+216 51 787 812",
    field: "GLSI",
    year: 2,
    motivation: "Aymen(isamm) 9ali",
    projects: "En cours",
    skills: "Sport (musculation) peinture",
    status: "offline",
    avatar: "/avatars/ghrir-yomma.png",
    points: 340,
  },
  {
    id: "15",
    name: "Amin Silit",
    firstName: "Amin",
    lastName: "Silit",
    email: "aminist004@gmail.com",
    phone: "+216 29 300 254",
    field: "GLSI",
    year: 3,
    motivation: "N7eb azouz",
    projects: "Camera cache",
    skills: "Créativité",
    status: "online",
    avatar: "/avatars/amin-silit.png",
    points: 310,
  },
  {
    id: "16",
    name: "Mohamed Khalil Denouche",
    firstName: "Mohamed Khalil",
    lastName: "Denouche",
    email: "Kobroula0@gmail.com",
    phone: "+216 29 084 198",
    field: "GLSI",
    year: 1,
    motivation: "Pour développer mes compétences",
    projects: "En cours",
    skills: "Dynamique créatif",
    status: "offline",
    avatar: "/avatars/khalil-denouche.png",
    points: 280,
  },
  {
    id: "17",
    name: "Mohamed Selby",
    firstName: "Mohamed",
    lastName: "Selby",
    email: "medsair8915@gmail.com",
    phone: "+216 99 123 371",
    field: "GLSI",
    year: 1,
    motivation: "To have fun",
    projects: "Micro trottoir ou matchy version istic",
    skills: "Cyber security and social activities",
    status: "online",
    avatar: "/avatars/mohamed-selby.png",
    points: 450,
  },
  {
    id: "18",
    name: "Youssef Agnbi",
    firstName: "Youssef",
    lastName: "Agnbi",
    email: "youssefeph250@gmail.com",
    phone: "+216 29 638 940",
    field: "GLSI",
    year: 3,
    motivation: "Améliorez la vie associative au sein de l'institut",
    projects: "En cours",
    skills: "Communication, résolution des problèmes, créativité",
    status: "offline",
    avatar: "/avatars/youssef-agnbi.png",
    points: 520,
  },
  {
    id: "19",
    name: "Eya Ssekk",
    firstName: "Eya",
    lastName: "Ssekk",
    email: "eyasseok74@gmail.com",
    phone: "+216 55 087 415",
    field: "GLSI",
    year: 3,
    motivation: "Pour être actif dans la vie du campus",
    projects: "Tournoi rami/ ri7la lblasa 5adhra/ soirée sans alcool",
    skills: "Communication, Planning",
    status: "online",
    avatar: "/avatars/eya-ssekk.png",
    points: 780,
  },
  {
    id: "20",
    name: "Elaa Chaamashi",
    firstName: "Elaa",
    lastName: "Chaamashi",
    email: "Chaamashikeba@gmail.com",
    phone: "+216 52 513 777",
    field: "GLSI",
    year: 3,
    motivation: "Les ahbeb",
    projects: "Musique",
    skills: "Musique",
    status: "offline",
    avatar: "/avatars/elaa-chaamashi.png",
    points: 390,
  },
  {
    id: "21",
    name: "Andel Belgacemi",
    firstName: "Andel",
    lastName: "Belgacemi",
    email: "andelpasemi@gmail.com",
    phone: "+216 94 601 187",
    field: "GLSI",
    year: 3,
    motivation: "New experience and self emprov",
    projects: "Podcast",
    skills: "Eager to learn everything",
    status: "online",
    avatar: "/avatars/andel-belgacemi.png",
    points: 610,
  },
  {
    id: "22",
    name: "Nour Manal",
    firstName: "Nour",
    lastName: "Manal",
    email: "Noormanal456@gmail.com",
    phone: "+216 26 594 408",
    field: "LISI",
    year: 1,
    motivation: "Pour être plus active",
    projects: "Podcast",
    skills: "Communication",
    status: "offline",
    avatar: "/avatars/nour-manal.png",
    points: 290,
  },
  {
    id: "23",
    name: "Mira Oueritalani",
    firstName: "Mira",
    lastName: "Oueritalani",
    email: "miragc2006@gmail.com",
    phone: "+216 21 654 440",
    field: "GLSI",
    year: 1,
    motivation: "Khater barcha jaww",
    projects: "istic يوميات فاكالوريا",
    skills: "Public speaking, na3rf nsafa9, barcha jaww",
    status: "online",
    avatar: "/avatars/mira-oueritalani.png",
    points: 470,
  },
  {
    id: "24",
    name: "Arij Yahyaoui",
    firstName: "Arij",
    lastName: "Yahyaoui",
    email: "yahyaouiarijyahyaoui@gmail.com",
    phone: "+216 28 287 686",
    field: "GLSI",
    year: 1,
    motivation: "Il semble intéressant",
    projects: "Pas encore",
    skills: "Toujours actif",
    status: "offline",
    avatar: "/avatars/arij-yahyaoui.png",
    points: 320,
  },
  {
    id: "25",
    name: "Feryel Mekli",
    firstName: "Feryel",
    lastName: "Mekli",
    email: "feryelmekhi0@gmail.com",
    phone: "+216 96 573 828",
    field: "GLSI",
    year: 2,
    motivation: "Membre de Radio Istic",
    projects: "En cours",
    skills: "En développement",
    status: "online",
    avatar: "/avatars/feryel-mekli.png",
    points: 260,
  },
  {
    id: "26",
    name: "Med Ali Bilibas",
    firstName: "Med Ali",
    lastName: "Bilibas",
    email: "dali.kabin.007@gmail.com",
    phone: "+216 59 607 495",
    field: "GLSI",
    year: 1,
    motivation: "Yes",
    projects: "Yes",
    skills: "Enthousiaste",
    status: "offline",
    avatar: "/avatars/medali-bilibas.png",
    points: 240,
  },
  {
    id: "27",
    name: "Gabsi Ilef",
    firstName: "Gabsi",
    lastName: "Ilef",
    email: "Ilefgabsi465@gmail.com",
    phone: "+216 52 234 837",
    field: "LAI",
    year: 2,
    motivation: "Membre actif",
    projects: "En cours",
    skills: "En développement",
    status: "online",
    avatar: "/avatars/gabsi-ilef.png",
    points: 210,
  },
  {
    id: "28",
    name: "Mariem Sasi",
    firstName: "Mariem",
    lastName: "Sasi",
    email: "sittimariemi@gmail.com",
    phone: "+216 93 087 209",
    field: "IOT",
    year: 2,
    motivation: "Meb3a nassim",
    projects: "Hata idee",
    skills: "Presentation",
    status: "offline",
    avatar: "/avatars/mariem-sasi.png",
    points: 330,
  },
  {
    id: "29",
    name: "Mustapha Sahli",
    firstName: "Mustapha",
    lastName: "Sahli",
    email: "mustafasahli199@gmail.com",
    phone: "+216 54 520 805",
    field: "LT",
    year: 1,
    motivation: "Jaw",
    projects: "Podcast avec partie por hight tck news hajet t5os tranche dage mta3 les etudiant",
    skills: "Barcha jaw",
    status: "online",
    avatar: "/avatars/mustapha-sahli.png",
    points: 560,
  },
  {
    id: "30",
    name: "Amal Maheni",
    firstName: "Amal",
    lastName: "Maheni",
    email: "amoulamahani@gmail.com",
    phone: "+216 53 580 405",
    field: "GLSI",
    year: 3,
    motivation: "Oui",
    projects: "Emission small business et emission news",
    skills: "Communication",
    status: "offline",
    avatar: "/avatars/amal-maheni.png",
    points: 640,
  },
  {
    id: "31",
    name: "Sinda Chekir",
    firstName: "Sinda",
    lastName: "Chekir",
    email: "sindachekir1808@gmail.com",
    phone: "+216 22 560 499",
    field: "GLSI",
    year: 1,
    motivation: "Je veux rejoindre Radio ISTIC pour découvrir le monde des médias et voir ce qui me plaît le plus.",
    projects:
      "Pour l'instant, je n'ai pas encore d'idée précise, mais j'aimerais participer à différents types de projets.",
    skills: "Je suis débutante mais motivée à apprendre. Je suis sérieuse, curieuse et j'aime travailler en groupe.",
    status: "online",
    avatar: "/avatars/sinda-chekir.png",
    points: 410,
  },
  {
    id: "32",
    name: "Eya Bourcheni",
    firstName: "Eya",
    lastName: "Bourcheni",
    email: "Bourcheniaya@gmail.com",
    phone: "+216 20 940 583",
    field: "LAI",
    year: 2,
    motivation: "Membre de Radio Istic",
    projects: "En cours",
    skills: "En développement",
    status: "offline",
    avatar: "/avatars/eya-bourcheni.png",
    points: 190,
  },
  {
    id: "33",
    name: "Mouadh Nasr",
    firstName: "Mouadh",
    lastName: "Nasr",
    email: "mouadhnasr85@gmail.com",
    phone: "+216 90 334 532",
    field: "LISI",
    year: 1,
    motivation: "Pour faire le jaw",
    projects: "Tournoi box 🥊",
    skills: "N7b jaw",
    status: "online",
    avatar: "/avatars/mouadh-nasr.png",
    points: 490,
  },
  {
    id: "34",
    name: "Mahdi Bernadi",
    firstName: "Mahdi",
    lastName: "Bernadi",
    email: "mahokoch.ratki@gmail.com",
    phone: "+216 97 771 299",
    field: "LISI",
    year: 1,
    motivation: "Nhebou jaw",
    projects: "Autre",
    skills: "Autre",
    status: "offline",
    avatar: "/avatars/mahdi-bernadi.png",
    points: 220,
  },
  {
    id: "35",
    name: "Rahma Hajaji",
    firstName: "Rahma",
    lastName: "Hajaji",
    email: "Rahmahajaji554@gmail.com",
    phone: "+216 99 651 366",
    field: "LAI",
    year: 2,
    motivation: "Membre de Radio Istic",
    projects: "En cours",
    skills: "En développement",
    status: "online",
    avatar: "/avatars/rahma-hajaji.png",
    points: 270,
  },
  {
    id: "36",
    name: "Lina Mouithi",
    firstName: "Lina",
    lastName: "Mouithi",
    email: "teriamouithi@gmail.com",
    phone: "+216 24 399 291",
    field: "LAI",
    year: 2,
    motivation: "Membre de Radio Istic",
    projects: "En cours",
    skills: "En développement",
    status: "offline",
    avatar: "/avatars/lina-mouithi.png",
    points: 250,
  },
  {
    id: "37",
    name: "Medeleh Maheim",
    firstName: "Medeleh",
    lastName: "Maheim",
    email: "matrimedelehi90@gmail.com",
    phone: "+216 21 885 209",
    field: "LAI",
    year: 2,
    motivation: "Membre de Radio Istic",
    projects: "En cours",
    skills: "En développement",
    status: "online",
    avatar: "/avatars/medeleh-maheim.png",
    points: 230,
  },
  {
    id: "38",
    name: "Self eddine Zouaoui",
    firstName: "Self eddine",
    lastName: "Zouaoui",
    email: "Selfocussal@gmail.com",
    phone: "+216 25 020 231",
    field: "LT",
    year: 1,
    motivation: "Membre de Radio Istic",
    projects: "En cours",
    skills: "En développement",
    status: "offline",
    avatar: "/avatars/self-zouaoui.png",
    points: 200,
  },
  {
    id: "39",
    name: "Nour el houda Sousi",
    firstName: "Nour el houda",
    lastName: "Sousi",
    email: "nousseuf790@gmail.com",
    phone: "+216 28 703 053",
    field: "LAI",
    year: 2,
    motivation: "For the fun",
    projects: "Dont have for the moment",
    skills: "Communication",
    status: "online",
    avatar: "/avatars/nour-sousi.png",
    points: 360,
  },
  {
    id: "40",
    name: "Aziz Wertami",
    firstName: "Aziz",
    lastName: "Wertami",
    email: "aziz.wertamite@gmail.com",
    phone: "+216 96 615 802",
    field: "GLSI",
    year: 3,
    motivation: "Help devollopong the club",
    projects: "Des idées dans le domaine sportif",
    skills: "Club,event management",
    status: "offline",
    avatar: "/avatars/aziz-wertami.png",
    points: 890,
  },
  {
    id: "41",
    name: "Youssef Tourni",
    firstName: "Youssef",
    lastName: "Tourni",
    email: "youssef50070@gmail.com",
    phone: "+216 29 792 041",
    field: "GLSI",
    year: 2,
    motivation: "Membre de Radio Istic",
    projects: "En cours",
    skills: "Reparation des systemes informatique, Excellentes compétences en communication et en persuasion",
    status: "online",
    avatar: "/avatars/youssef-tourni.png",
    points: 580,
  },
]

export const membersData = members

export const bureauMembers = members.filter((m) => m.isBureau)
